version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    command: elasticsearch -Etransport.host=127.0.0.1

  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MS_TRANSLATOR_KEY=${MS_TRANSLATOR_KEY}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
    depends_on:
      - elasticsearch
