"""new fields in user model

Revision ID: 357412bc4101
Revises: cc8d7d988719
Create Date: 2019-04-01 15:08:29.444422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357412bc4101'
down_revision = 'cc8d7d988719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
