"""add language to posts

Revision ID: 444785e1b0bc
Revises: cb8dc844491a
Create Date: 2019-04-12 00:48:51.857971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444785e1b0bc'
down_revision = 'cb8dc844491a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
